### PR TITLE
NetworkImage React Component

### LINKED ISSUE #832: Improve handling of broken images in React Native
A (small) downside of refactoring in React Native is we don't have the `SDWebImage` library to handle loading and error images. The React Native repo seems to have [good examples](https://github.com/facebook/react-native/blob/8f19f5bef4a86c046fd9dd0ad5501f6bb5bbd6c4/Examples/UIExplorer/ImageExample.js#L31) of how to recreate this.

Currently using placekitten holders for when an image doesn't exist.. but when the image gives a 404, we get a blank image.

### PR DESCRIPTION
**Pull request by aaronschachter**
Closes #832: Display Loading and Error assets for network images in React Native, removing most placekitten images :crying_cat_face: 

Also bonus sweet progress indicator for Reportbacks, Cover Images:

simulator screen shot feb 25 2016 9 45 10 am
simulator screen shot feb 25 2016 12 07 09 pm

### CODE REVIEW

File: ReactComponents/CampaignView.js [hunk 1]
```diff
@@ -14,9 +14,11 @@ import React, {
 import Dimensions from 'Dimensions';
 
 var Style = require('./Style.js');
+var Helpers = require('./Helpers.js');
```
Comment (aaronschachter) [inline ReactComponents/CampaignView.js]: Don't actually need this
