### PR TITLE
Safety checks on User Profile

### LINKED ISSUE #958: App crash on profile - check for user.country
https://fabric.io/do-something/ios/apps/org.dosomething.letsdothis/issues/56d5985bf5d3a7f76b385186/sessions/ac828b89acc34419ae114a361a0f6364

Crash occurred after uploading an avatar:
> Fatal Exception: RCTFatalException: Unhandled JS Exception: null is not an object (evaluating 'this.state.user.country.length')
Unhandled JS Exception: null is not an object (evaluating 'this.state.user...., stack: renderHeader@18:3837

Logs:
> 	__68-[DSOUserManager continueSessionWithCompletionHandler:errorHandler:]_block_invoke line 132 $ user 56e73804469c64d9578b5d69
1	|	22:47:10:171	|	-[GAI(LDT) trackScreenView:] line 19 $ news
2	|	22:47:12:123	|	-[LDTTabBarController tabBarController:didSelectViewController:] line 255 $ selectedIndex 2
3	|	22:47:12:305	|	-[LDTTabBarController tabBarController:didSelectViewController:] line 255 $ selectedIndex 2
4	|	22:47:12:356	|	-[GAI(LDT) trackScreenView:] line 19 $ user-profile/self
5	|	22:47:15:338	|	-[GAI(LDT) trackEventWithCategory:action:label:value:] line 28 $ account:change avatar:(null):(null)
6	|	22:47:26:603	|	-[GAI(LDT) trackScreenView:] line 19 $ user-profile/self
7	|	22:47:27:755	|	__78-[DSOUserManager postAvatarImage:sendAppEvent:completionHandler:errorHandler:]_block_invoke line 221 $ <UIImage: 0x157cf0e0> size {640, 640} orientation 0 scale 1.000000

### LINKED ISSUE #961: Profile needs to check for existence of responseData.data
If we get a networking error on the profile (like in https://github.com/DoSomething/northstar/issues/313), we crash because `signups.length` is undefined

### PR DESCRIPTION
**Pull request by aaronschachter**
* Closes #961, checking for existence of a `responseData.error` and only calling `loadSignups` if `responseData.data` exists
* Closes #958, I think. I can't replicate this but this was previously optimistic code, expecting that `data.country` would exist every time we get a response back from the API. Looks it didn't in #958, so this PR tidies up the `[DSOAPI postAvatarForUser:avatarImage:completionHandler:errorHandler:]` to return a `DSOUser`, which should be created with proper object.property checks, instead blindly trusting whatever `id` we get back from API

### CODE REVIEW

File: Lets Do This/Networking/DSOUserManager.m [hunk 1]
```diff
@@ -216,16 +216,12 @@ - (void)reportbackForCampaign:(DSOCampaign *)campaign fileString:(NSString *)fil
...
-    [[DSOAPI sharedInstance] postAvatarForUser:[DSOUserManager sharedInstance].user avatarImage:avatarImage completionHandler:^(id responseObject) {
-        CLS_LOG(@"%@", avatarImage);
-        NSDictionary *responseDict = responseObject[@"data"];
-        self.user.avatarURL = responseDict[@"photo"];
-        NSLog(@"postAvatarImage currentUserChanged eventDispatcher");
-        [[self appDelegate].bridge.eventDispatcher sendAppEventWithName:@"currentUserChanged" body:responseDict];
-
+- (void)postAvatarImage:(UIImage *)avatarImage completionHandler:(void(^)(DSOUser *))completionHandler errorHandler:(void(^)(NSError *))errorHandler {
+    [[DSOAPI sharedInstance] postAvatarForUser:[DSOUserManager sharedInstance].user avatarImage:avatarImage completionHandler:^(DSOUser *user) {
+        // @todo: hack for now, having trouble just updating avatar only in RN
```
Comment (aaronschachter) [inline Lets Do This/Networking/DSOUserManager.m]: This is what the `sendAppEvent` param aimed to do, but we weren't even using within this method for the same reason . Tried creating a separate `state.photo` property in `UserView` (to avoid reloading the user's entire profile) but couldn't get it to work. This comment is more to document that I still couldn't get it to work :crying_cat_face:

File: ReactComponents/UserView.js [hunk 2]
```diff
@@ -91,10 +91,21 @@ var UserView = React.createClass({
       .then((response) => response.json())
       .catch((error) => this.catchError(error))
       .then((responseData) => {
+        // This was added here -- https://github.com/DoSomething/LetsDoThis-iOS/pull/853#discussion_r54018442
+        // If we turn on airplane mode and load this view, the catchError executes above 
+        // but this then block still executes. feels like i'm doing something wrong here.
         if (!responseData) {
```
Comment (aaronschachter) [inline ReactComponents/UserView.js]: Also documents weirdness of why we need this (https://github.com/DoSomething/LetsDoThis-iOS/pull/853#discussion_r54018442)
