### PR TITLE
NetworkErrorView

### LINKED ISSUE #620: Handle internal errors on User Profile
For any internal errors, we currently display a blank profile. 

simulator screen shot nov 13 2015 10 32 27 am

I think best approach here would be to Epic Fail, but the Try Again button actually pops back to the screen the user was on before. We'll want to change the "Try Again" button text to something else like  "Go back"... with the title/subtitle perhaps using the "Oops our bad" text.
 
Possible scenarios:
* we happen to have a null user on a Reportback Item, currently we get a "Resource does not exist" error from the returned 404 response, in screenshot below
* Northstar user does not contain signups, so blank profile
* Any other 400/500 errors returned

### LINKED ISSUE #664: Handle internal errors on Campaign Detail
Similar to #620 -- we should handle errors better on the Campaign Detail. If the API request for photos fails to load, we could potentially display an Epic Fail view within the "Who's Doing it Now" section, or just push up to the VC with a Try Again. If there's internally a 503 error, this isn't really the best solution (but then again, we display Epic Fail forever until we get rid of 503's on the Main Feed)

### LINKED ISSUE #773: Handle NewsFeedView networking errors
Call `LDTMessage` for any HTTP / no connection errors.

* [ ] Handle errors from News Feed API
* [ ] Don't load Full Article if user is not connected

### PR DESCRIPTION
**Pull request by aaronschachter**
Adds new React Component to inform when a network error has occurred, and prompts user to tap to retry loading.
* Closes #773 
* Closes #664 
* Closes #620

TODO: 
* DRY the Loading Views.. potentially refactor this as just a `NetworkRequestView` to handle both?

simulator screen shot feb 24 2016 2 14 28 pm

### CODE REVIEW

File: ReactComponents/CampaignView.js [hunk 1]
```diff
@@ -60,10 +62,20 @@ var CampaignView = React.createClass({
...
+      loaded: false,
+    });
+    var statusUrl = this.props.signupUrl;
+    statusUrl += '&campaigns=' + this.props.campaign.id.toString();
     fetch(statusUrl)
       .then((response) => response.json())
+      .catch((error) => this.catchError(error))
       .then((responseData) => {
+        if (!responseData) {
+          return;
```
Comment (aaronschachter) [inline ReactComponents/CampaignView.js]: Without this, the code still continues even if we call the `catchError` :confused:

File: ReactComponents/NetworkErrorView.js [hunk 2]
```diff
@@ -0,0 +1,64 @@
...
+var NetworkErrorView = React.createClass({
+  render: function() {
+    return (
+      <View style={styles.container}>
+        <TouchableHighlight onPress={this.props.retryHandler}>
+
+        <View style={styles.button}>
+          <Image
+            style={styles.image}
+            source={{uri: 'Fail Icon'}}
```
Comment (aaronschachter) [inline ReactComponents/NetworkErrorView.js]: Workaround... using `require` causes the build to fail for me :frowning: #851
